name: unittest
description: Runs .NET unit tests under a specified configuration

inputs:
  project:
    default: ""
    description: The test project
    required: true
  name:
    required: true
    description: Machine-friendly name of the test project
  title:
    required: true
    description: Human-friendly name of the test project
  github-token:
    description: GitHub token so that test results can be uploaded
    required: true

runs:
  using: composite
  steps:
  - run: dotnet test
      "${{ inputs.project }}"
      --no-restore
      --logger "GitHubActions;report-warnings=true"
      --logger "trx;LogFileName=${{ github.workspace }}/artifacts/test/unit-test-results-${{ inputs.name }}-Debug.trx"
      --configuration Debug
      -p:WarningLevel=0
    shell: bash
  - run: dotnet test
      "${{ inputs.project }}"
      --no-restore
      --logger "GitHubActions;report-warnings=true"
      --logger "trx;LogFileName=${{ github.workspace }}/artifacts/test/unit-test-results-${{ inputs.name }}-Release.trx"
      --configuration Release
      -p:WarningLevel=0
    shell: bash
  - uses: ./.github/test-report
    with:
      trx-path: artifacts/test/unit-test-results-${{ inputs.name }}-Debug.trx
      report-name: ${{ inputs.name }}-Debug-${{ runner.os }}
      report-title: ${{ inputs.title }} (Debug) on ${{ runner.os }}
      github-token: ${{ inputs.github-token }}
