name: publish-public

on:
  workflow_dispatch:
    inputs:
      nuget-package-names:
        type: string
        default: ""
        description: NuGet packages to copy
        required: false
      npm-package-names:
        type: string
        default: ""
        description: npm packages to copy
        required: false
      version:
        type: string
        default: ""
        description: The version of packages to copy
        required: true

jobs:
  copy:
    name: Copy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:

      - uses: nuget/setup-nuget@v1

      - name: Authenticate with NuGet internal feed
        run: >
          nuget add source `
            --username "${{ secrets.AZURE_ARTIFACTS_USERNAME }}" `
            --password "${{ secrets.AZURE_ARTIFACTS_PAT }}" `
            --store-password-in-clear-text `
            --name internal `
            "${{ secrets.AZURE_ARTIFACTS_FEED }}"

      - name: Copy NuGet packages
        run: >
          mkdir packages
          "${{ inputs.nuget-package-names }}".Split(",") | ForEach-Object {
            nuget install "$_" `
              -DirectDownload `
              -NonInteractive `
              -SolutionDirectory "/dev/null" `
              -OutputDirectory packages `
              -Version "${{ inputs.version }}" `
              -Source internal
            nuget push "packages/$_.${{ inputs.version }}/$_.${{ inputs.version }}.nupkg"`
              -Source "${{ secrets.PUBLIC_NUGET_FEED }}" `
              -ApiKey "${{ secrets.PUBLIC_NUGET_API_KEY }}" `
              -NonInteractive
          }
