name: publish-public

on:
  workflow_dispatch:
    inputs:
      os:
        type: string
        default: "ubuntu-latest"
        description: The OS to run the tests on
        required: false
      browser:
        type: choice
        options:
          - chrome
          - firefox
        default: "chrome"
        description: The browser to run the tests in
        required: false
      environment:
        type: choice
        options:
          - Development
          - Production
        default: "Development"
        description: The AspNetCore environment
        required: false
      samples-config:
        type: choice
        options:
          - Default
          - KnockoutDeferUpdates
          - ExplicitAssemblyLoading
          - ServerSideViewModelCache
          - LazyCsrfToken
          - ExperimentalFeaturesTests
        default: "Default"
        description: The samples config to use
        required: false

jobs:
  ui-tests:
    name: UI tests
    runs-on: ${{ inputs.os }}
    timeout-minutes: 50
    strategy:
      fail-fast: false # don't kill tests when one environment fails
      matrix:
        # specify only one config, all other configurations are included explicitly
        browser: [chrome]
        os: [ubuntu-latest]
        environment: [Production]
        samples-config: [Default]
        include:
          - browser: chrome
            os: windows-2022
            environment: Development
            samples-config: Default
          - browser: firefox
            os: ubuntu-latest
            environment: Development
            samples-config: Default
          - browser: firefox
            os: ubuntu-latest
            environment: Production
            samples-config: Default
          - browser: firefox
            os: ubuntu-latest
            environment: Production
            samples-config: ExperimentalFeaturesTests
          - browser: chrome
            os: ubuntu-latest
            environment: Development
            samples-config: ExperimentalFeaturesTests

    env:
      SLN: "${{ inputs.os == 'windows-2022' && 'src/DotVVM.sln' || 'src/DotVVM.Crossplatform.slnf' }}"
    steps:
    - uses: actions/checkout@v3
    - name: Set up
      uses: ./.github/setup
      with:
        sln: ${{ env.SLN }}
    - name: Run UI tests
      uses: ./.github/uitest
      with:
        browser: ${{ inputs.browser }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        build-configuration: "${{ inputs.environment == 'Production' && 'Release' || 'Debug' }}"
        runtime-environment: "${{ inputs.environment }}"
        samples-config: "${{ inputs.samples-config }}"
