name: ui-tests-manual

on:
  workflow_dispatch:
    inputs:
      os:
        type: string
        default: "ubuntu-latest"
        description: The OS to run the tests on
        required: true
      browser:
        type: choice
        options:
          - chrome
          - firefox
        default: "chrome"
        description: The browser to run the tests in
        required: true
      environment:
        type: choice
        options:
          - Development
          - Production
        default: "Development"
        description: The AspNetCore environment
        required: true
      build-configuration:
        type: choice
        options:
          - Debug
          - Release
        default: "Debug"
        description: The MSBuild configuration
        required: true
      samples-config:
        type: choice
        options:
          - Default
          - KnockoutDeferUpdates
          - ExplicitAssemblyLoading
          - ServerSideViewModelCache
          - LazyCsrfToken
          - ExperimentalFeaturesTests
        default: "Default"
        description: The samples config to use
        required: true
      timeout:
        type: number
        default: 50
        description: The timeout in minutes
        required: true

jobs:
  ui-tests:
    name: UI tests
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout }}
    env:
      SLN: "${{ inputs.os == 'windows-2022' && 'src/DotVVM.sln' || 'src/DotVVM.Crossplatform.slnf' }}"
    steps:
    - uses: actions/checkout@v3
    - name: Set up
      uses: ./.github/setup
      with:
        sln: ${{ env.SLN }}
    - name: Run UI tests
      uses: ./.github/uitest
      with:
        browser: ${{ inputs.browser }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        build-configuration: "${{ inputs.build-configuration }}"
        runtime-environment: "${{ inputs.environment }}"
        samples-config: "${{ inputs.samples-config }}"
